### ISSUE TITLE
Final Review Page units are spaced too far from the value

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-reporting#587]
Problem: In Compliance Summary section, the units are too far from the value, affecting the readability
- [ ] Units are too far away from the field value. Reduce the spacing to 10px between the value and the unit
![Image](https://github.com/user-attachments/assets/dd02ded1-1a75-4c97-a2da-352ac88ddfc6)

- [ ] Emissions fields are not aligned under activities
[ ]<img width="690" alt="Image" src="https://github.com/user-attachments/assets/660146ca-02bf-4352-b264-de23452951ee" />

**Comment by zoeyli-46** [comment]
@patriciarussellCAS design backlog ticket for the final review LFO page

**Comment by patriciarussellCAS** [comment]
@zoeyli-46 - based on your latest review, I wonder if this ticket is no longer needed?

**Comment by zoeyli-46** [comment]
Hey @patriciarussellCAS ! Sorry, I meant specifically the allocation of emissions page doesn't have the zig zag pattern anymore, but it is still there for the Emissions section under Activities. Yes unfortunately this ticket is still relevant :D

**Comment by patriciarussellCAS** [comment]
@zoeyli-46 I think this issue was fixed with the latest updates but let me know if I'm wrong!

**Comment by zoeyli-46** [comment]
@patriciarussellCAS it's still an issue for submitted reports cc @ayeshmcg 

If the report status is submitted, the report has misaligned inputs on the final review page
<img width="711" height="493" alt="Image" src="https://github.com/user-attachments/assets/7a9c6e45-da9a-4403-9c87-4110a47af67a" />

If the report status is not submitted, then the final review page is aligned, but the spacing is still far apart

<img width="1038" height="88" alt="Image" src="https://github.com/user-attachments/assets/dc197189-3705-4923-8c28-02492e288d3f" />
