### ISSUE TITLE
Bug: LFO navigation from Additional Reporting page

### ISSUE THREAD

**Issue by fviduya** [bcgov/cas-reporting#598]
#### Describe the Bug:

The `Back` button from LFO's Additional Reporting Data page goes back to first facility's Allocation of Emissions page.

#### Probability: 5

(How likely the bug is to happen, scored from 1-5. For example, probability of 5 is something like "it happens to all users every time they log in." whereas probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

#### Impact:

(How bad the bug is when it does happen, scored from 1-5. For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected." whereas effect of 1 is "It makes some styling look a little bit weird.")

<img src="https://www.getzephyr.com/sites/default/files/riksk%20matrix.jpg" alt="Bug Matrix" width="250" height="250"/>

#### Steps to reproduce the behaviour:

1. Log in as industry user (used bc-cas-dev)
2. Navigate to Submit Annual Report(s)
3. Click Start/Continue for Banana LFO
4. Fill out required fields until all report for facilities have been completed in the Report Information page
5. Click `Save & Continue` from the Report Information page, the page should route to Additional Reporting Data
6. Click `Back` button from the Additional Reporting Data page

Expected Result: Page redirects to the Report Information page 
Actual Result: Page redirects to first facility's Allocation of Emissions page

#### Screenshots:

https://github.com/user-attachments/assets/361f4450-bc2b-453f-b72c-c3a9b7d845d7

#### Additional information:

Browser: [e.g. chrome, safari]
Version: [e.g. 22]

#### Additional Context

-

**Comment by patriciarussellCAS** [comment]
Could be fixed by #567

**Comment by shon-button** [comment]
@fviduya 
@pbastia 

I don't believe this issue has been resolved by https://github.com/bcgov/cas-reporting/issues/567

FROM DEV:
![Image](https://github.com/user-attachments/assets/6c2e4d30-4390-4a86-828d-613aaeac8683)
`Save & Continue`
![Image](https://github.com/user-attachments/assets/25fccc47-3d20-43e5-8fd8-c2af71051aaa)
`Back`
![Image](https://github.com/user-attachments/assets/5ca87011-f1ab-4d12-a513-5e4f6ef2556b)

**Comment by fviduya** [comment]
Hi @shon-button, thanks for checking that! Based on my test as well, it's not yet fixed so I'll be moving this back to Sprint Backlog 🙂

**Comment by shon-button** [comment]
@ayeshmcg 

This is fixed here: https://github.com/bcgov/cas-registration/pull/3070

**Comment by shon-button** [comment]
@fviduya 
Fix made in PR [fix: report flows](https://github.com/bcgov/cas-registration/pull/3070)

**Comment by fviduya** [comment]
I have tested this in the DEV environment, [here is the test document for reference](https://buttoninc-my.sharepoint.com/:w:/g/personal/francesca_button_is/EewQVvg_wOtPu1_oIQhV8rEBZI80tjyFwKpHPW2VC-l7dA?e=WOBqh1).

I can verify that:
- [x] `Back` button from the Additional Reporting Data page navigates back to the Report Information page 
- [x] `Save & Continue` from the Report Information page routes to Additional Reporting Data page

Moving to Pending PO for review of test. Thank you!

**Comment by patriciarussellCAS** [comment]
Reviewed test doc. Moving to accepted.
